Repository VectorInstitute/odyssey, pull requests merged in 2024-05, with the labels that each got.

#34 Fixed issues with Mamba Finetune pipeline
  finetune.py
  odyssey/models/cehr_big_bird/model.py
  odyssey/models/cehr_mamba/mamba_utils.py
  odyssey/models/cehr_mamba/model.py
  odyssey/models/configs/cehr_mamba.yaml
  pretrain.py
Labels: bug

#33 Update slurm_scripts.md
  slurm_scripts.md
Labels: documentation

#39 Refactor sequence generation to be modular
  finetune.py
  odyssey/data/DataProcessor.ipynb
  odyssey/data/constants.py
  odyssey/data/dataset.py
  odyssey/data/processor.py
  odyssey/data/sequence.py
  odyssey/evals/TestAnalysis.ipynb
  odyssey/interp/AttentionVisualization.ipynb
  odyssey/models/cehr_big_bird/model.py
  odyssey/models/cehr_mamba/mamba-dev.ipynb
  odyssey/models/cehr_mamba/mamba_utils.py
  poetry.lock
  pyproject.toml
Labels: refactor

#45 Update readme
  README.md
Labels: documentation

#49 Update README.md
  README.md
Labels: documentation

#50 Implemented EHRMamba
  finetune.py
  odyssey/data/DataProcessor.ipynb
  odyssey/data/dataset.py
  odyssey/evals/TestAnalysis.ipynb
  odyssey/evals/evaluation.py
  odyssey/evals/prediction.py
  odyssey/models/baseline/Bi-LSTM.ipynb
  odyssey/models/baseline/XGBoost.ipynb
  odyssey/models/cehr_big_bird/model.py
  odyssey/models/cehr_big_bird/playground.ipynb
  odyssey/models/cehr_big_bird/tokenizer.ipynb
  odyssey/models/configs/cehr_bigbird.yaml
  odyssey/models/configs/cehr_multibird.yaml
  odyssey/models/ehr_mamba/__init__.py
  odyssey/models/ehr_mamba/mamba-dev.ipynb
  odyssey/models/ehr_mamba/mamba_utils.py
  odyssey/models/ehr_mamba/model.py
  odyssey/models/ehr_mamba/playground.ipynb
  pretrain.py
Labels: bug, enhancement, refactor

#51 Updated readme and notebook files
  odyssey/models/ehr_mamba/mamba-dev.ipynb
  odyssey/models/ehr_mamba/playground.ipynb
  results.md
  slurm_scripts.md
Labels: documentation, refactor
