Repository VectorInstitute/odyssey, pull requests merged in 2024-06, with the labels that each got.

#52 Added Mamba Config
  odyssey/models/configs/ehr_mamba.yaml
  odyssey/models/ehr_mamba/model.py
Labels: bug, good first issue

#59 Add ignore to docstring to be compatible with HF
  odyssey/models/ehr_mamba/mamba_utils.py
Labels: documentation

#56 Fix issues with EHRMamba generation
  odyssey/evals/__init__.py
  odyssey/evals/prediction.py
  odyssey/interp/attribution.py
  odyssey/interp/utils.py
  odyssey/models/ehr_mamba/mamba_utils.py
Labels: bug

#60 Refactor dataset.py to use standard practices.
  odyssey/data/dataset.py
  tests/__init__.py
  tests/odyssey/__init__.py
  tests/odyssey/data/__init__.py
  tests/odyssey/data/mimiciv/__init__.py
  tests/odyssey/data/test_dataset.py
  tests/odyssey/utils/__init__.py
Labels: refactor
